---
- hosts: all
     
  vars_files:
  - vars/main.yml
  
  tasks:
    - name: run dhcp task file
      include_tasks: tasks/main.yml
      when: "{{ 'kalem-dhcp' in inventory_hostname }}"

    - name: run app task file
      include_tasks: tasks/main.yml
      when: "'app' in group_names"

  roles:
    -  {  role: gateway,  when: '"kalem-gateway" in inventory_hostname' }
    -  {  role: dns,  when: '"kalem-dns" in inventory_hostname' }
   
