---
  - name: subscription-manager refresh
    command: subscription-manager refresh

  - name: install dhcp
    command: yum -y install dhcp

  # - name: install dhcp
  #   ansible.builtin.yum:
  #     name: dhcp

  - name: Update DHCP conf
    ansible.builtin.blockinfile:
      path: /etc/dhcp/dhcpd.conf 
      block: |
        option domain-name "{{DOMAIN_NAME}}"; 
        default-lease-time	86400;  
        max-lease-time 172800; 
        ddns-update-style none;
        authoritative;
        subnet {{SUBNET}} netmask 255.255.255.0 { 
        range {{RANGE}};  
        option subnet-mask 255.255.255.0; 
        option routers "{{OPTION_ROUTERS}}";   
        option domain-name "{{DOMAIN_NAME}}";  
        option domain-search "{{DOMAIN_NAME}}"; 
        option domain-name-servers {{DNS}}; 
        }
        host gateway-node {
          hardware ethernet {{ GW_MAC }}
          fixed-address {{ GW_IP }};    
        }
        host dhcp-node {
          hardware ethernet {{ DHCP_MAC }}
          fixed-address {{ DHCP_IP }};    
        }
        host dns-node {
          hardware ethernet {{ DNS_MAC }}
          fixed-address {{ DNS_IP }};    
        }
        
  - name: start dhcpd
    command: systemctl start dhcpd.service

  - ansible.posix.firewalld:
      service: dhcp
      permanent: yes
      state: enabled

  - name: reload firewall
    command: firewall-cmd --reload

  - name: Update ens224
    ansible.builtin.blockinfile:
      path: /etc/sysconfig/network-scripts/ifcfg-{{in_interface}}
      block: |
        DEFROUTE=yes
        GATEWAY={{ hostvars['kalem-gateway'].ansible_ens224.ipv4.address }};
        DOMAIN={{DOMAIN_NAME}}; 
  #  GATEWAY={{ hostvars['gateway'].ansible_host }} 
  # DNS1={{{ hostvars['dns'].ansible_host }}         
  - name: ifdown + ifup NIC
    command: ifdown {{in_interface}} && ifup {{in_interface}}

  - name: start DHCPd
    command: systemctl start dhcpd.service

  - name: add service DHCPd
    command: firewall-cmd --add-service=dhcp --permanent

  - name: reload firewall
    command: firewall-cmd --reload

  - name: if up
    command: ifup {{in_interface}}